version: "3.8"

volumes:
  prometheus_data: {}
  grafana_data: {}
  etc_pihole: {}
  etc_dnsmasq: {}
  uptime_kuma_data: {}

networks:
  front-tier:
  back-tier:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:v2.25.2
    user: "0"
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
    networks:
      - back-tier

  grafana:
    image: grafana/grafana:8.1.2
    user: "0"
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
    ports:
      - "3030:3000"
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier

  ping:
    image: prom/blackbox-exporter:latest
    restart: always
    volumes:
      - ./blackbox/config:/config
    command:
      - "--config.file=/config/blackbox.yml"
    ports:
      - "9115:9115"
    networks:
      - back-tier

  speedtest:
    image: miguelndecarvalho/speedtest-exporter:latest
    container_name: speedtest-exporter
    restart: always
    ports:
      - "9798:9798"
    networks:
      - back-tier

  nodeexp:
    image: prom/node-exporter:latest
    privileged: true
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - "9100:9100"
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - back-tier

  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: always
    volumes:
      - uptime_kuma_data:/app/data
    ports:
      - "3032:3001"
    networks:
      - front-tier
      - back-tier
